-- CLOUD ONLY. The RDS half of what the mysql image does for free on a laptop.
--
-- Two things do not port from db/init/01-local-grants.sql:
--
--   1. RDS has no MYSQL_USER, so `appuser` does not exist yet and must be created here.
--      Its password is generated by CloudFormation into Secrets Manager and injected
--      into the db-init container as $APP_PASSWORD; the container substitutes it into
--      the placeholder below, so the password never leaves the task and never touches
--      the workflow log or this repository.
--
--   2. `GRANT ALL PRIVILEGES ON *.*` is REJECTED on RDS: the master account is not a
--      superuser and cannot grant privileges it does not itself hold. Grants have to be
--      per schema, which is no loss — schema isolation is the rule anyway.
--
-- THIS FILE IS THE BOOTSTRAP ONLY, and deliberately does not list the ten modules.
-- Adding a team must not require an edit here, or eleven repos are coupled through one
-- file in one of them. A module's schema and its grant are created by the module's own
-- first deploy (infra/db-init-schema.sh, run by deploy-service.sh), from the DbName in
-- its own infra/env/<env>.params. So the honest content of this file is: the user, plus
-- the orchestrator's own schema.

CREATE USER IF NOT EXISTS 'appuser'@'%' IDENTIFIED BY '__APP_PASSWORD__';

-- Idempotent: re-running a deploy must not fail, and must repair a drifted password.
ALTER USER 'appuser'@'%' IDENTIFIED BY '__APP_PASSWORD__';

GRANT ALL PRIVILEGES ON `neo_00`.* TO 'appuser'@'%';

FLUSH PRIVILEGES;
